Create entities and repositories for them
ProstP/TravelLine2024.2 pull request #1
Opened 2024-10-11 15:23 UTC by ProstP

2024-10-14 06:04 UTC, Osch-1 requested changes

2024-10-14 06:04 UTC, Osch-1 commented on MaryFood/Infrastructure/Foundation/MaryFoodDbContext.cs
> +        modelBuilder.ApplyConfiguration( new UserConfiguration() );
#расскажи почему не используешь ApplyConfigurationsFromAssembly
хочу понимать почему делаешь так

2024-10-14 06:04 UTC, Osch-1 commented on MaryFood/Infrastructure/Foundation/Repository/Repository.cs
> +            _dbContext.SaveChanges();
SaveChanges точно нужен?

2024-10-14 06:04 UTC, Osch-1 commented on MaryFood/Infrastructure/Foundation/Repository/Repository.cs
> +        public List<T> GetAll()
такой метод лучше не создавать, так как его опасно использовать -> может быть выгружено очень много данных

2024-10-14 06:04 UTC, Osch-1 commented on MaryFood/Infrastructure/Foundation/Repository/Repository.cs
> +            _dbContext.SaveChanges();
здесь не нужно вызывать SaveChanges, будем использовать UnitOfWork

2024-10-14 06:04 UTC, Osch-1 commented on MaryFood/Domain/Repository/ITagRepository.cs
> +        public Tag? Get( int id );
давай во всех методах на async перейдем

2024-10-14 15:48 UTC, Osch-1 commented on MaryFood/Domain/Repository/ITagRepository.cs
> +        public Tag? Get( int id );
методы Get - async

2024-10-14 15:51 UTC, Osch-1 commented on MaryFood/Infrastructure/Foundation/MaryFoodDbContext.cs
> +        modelBuilder.ApplyConfiguration( new UserConfiguration() );
вернуть AppluConfiguration

2024-10-14 15:55 UTC, Osch-1 commented on MaryFood/Infrastructure/Foundation/EntityConfiguration/UserConfiguration.cs
> +            builder.Property( u => u.Password )
хранить хеш SHA-512
- почитать про SHA

2024-10-14 15:56 UTC, Osch-1 commented on MaryFood/Infrastructure/Foundation/EntityConfiguration/UserConfiguration.cs
> +            builder.Property( u => u.Password )
Password -> PasswordHash

2024-10-14 15:59 UTC, Osch-1 commented on MaryFood/Infrastructure/Foundation/EntityConfiguration/TagConfiguration.cs
> +            builder.HasMany( t => t.Recipes )
вынести в RecipeConfiguration

2024-10-14 16:03 UTC, Osch-1 commented on MaryFood/Domain/Repository/IRecipeStepRepository.cs
> +    public interface IRecipeStepRepository : IRepository<RecipeStep>
получать подсущности будем вместе с корневой сущностью
нужно почитать про Include

2024-10-14 16:07 UTC, Osch-1 commented on MaryFood/Domain/Entity/Tag.cs
> +        public MainTag? MainTag { get; private init; } = null;
https://learn.microsoft.com/en-us/ef/core/modeling/relationships/many-to-many#unidirectional-many-to-many

2024-10-14 16:08 UTC, Osch-1 commented on MaryFood/Domain/Entity/Recipe.cs
> +    public string Image { get; private init; }
тут решили

2024-10-14 16:08 UTC, Osch-1 commented on MaryFood/Domain/Entity/Recipe.cs
> +    [System.Text.Json.Serialization.JsonIgnore]
решили, убрать везде

2024-10-15 05:47 UTC, ProstP commented on MaryFood/Domain/Entity/User.cs
> +        public string Login { get; private init; }
Оставлю логин, во-первых привычнее, во-вторых в фигме там логин было написано, при авторизации и регистрации.

2024-10-16 11:06 UTC, Osch-1 commented on MaryFood/App/UnitOfWork/IUnitOfWork.cs
> +    void SaveChanges();
Поправь, пожалуйста, namespace везде

2024-10-16 14:17 UTC, ProstP commented on MaryFood/App/UnitOfWork/IUnitOfWork.cs
> +    void SaveChanges();
Это вроде старая версия, у меня итак namespace Application.Unit...

2024-10-16 17:02 UTC, Osch-1 approved these changes

2024-10-16 17:02 UTC, merged